[features]
seeds = false
[programs.localnet]
donate = "HH95eqLi8izRFNVob95g4URG62Jkf9HmtXLz5MFXyh7z"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/j.behlim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
